## La bibliothèque Numpy

In [1]:
import numpy as np

Mon 1er array

In [2]:
arr1=np.array([32,43,54,65],dtype=float)
print(arr1*2)

[  64.   86.  108.  130.]


In [3]:
list1=[32,43,54,65]

In [4]:
print(arr1.shape,arr1.dtype)

(4,) float64


Générez des arrays remplis de 0 et de 1 de taille 10.


In [5]:
arr2=np.ones(10)
arr3=np.zeros(10)

In [6]:
print( arr2*arr3)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [7]:
#construction d'une matrice 100 x 10 de nombres aléatoires suivant une distribution 
#normale centrée réduite
arr4=np.random.randn(1000).reshape(100,10)

Extraire les 5 premières colonnes et les 50 premiers individus

In [8]:
arr5=arr4[:50,:5]
arr5.shape

(50, 5)

In [9]:
arr5[4,4]

-0.40504675969595955

Calcul de X'X

In [10]:
arr6=np.dot((arr4).T,arr4)

In [11]:
np.corrcoef(arr4)

array([[ 1.        ,  0.00974831, -0.06753283, ..., -0.48524617,
         0.34370964,  0.48411687],
       [ 0.00974831,  1.        , -0.53384291, ..., -0.00764465,
         0.04490133,  0.39314302],
       [-0.06753283, -0.53384291,  1.        , ..., -0.53694899,
        -0.05802406, -0.67065935],
       ..., 
       [-0.48524617, -0.00764465, -0.53694899, ...,  1.        ,
        -0.23021884,  0.17901132],
       [ 0.34370964,  0.04490133, -0.05802406, ..., -0.23021884,
         1.        ,  0.17729692],
       [ 0.48411687,  0.39314302, -0.67065935, ...,  0.17901132,
         0.17729692,  1.        ]])

In [12]:
arr7=np.random.randn(1000000)
arr8=np.random.randn(1000000)

In [13]:
#approche 1
def transfo(arr):
    for i in range(len(arr)):
        if arr[i]<0:
            arr[i]=0
    return arr

In [14]:
%time arr8=transfo(arr7)

Wall time: 439 ms


In [15]:
#approche 2
%time arr8=np.where(arr8<0,0,arr8)

Wall time: 5 ms


In [16]:
#clacul de la moyenne
arr8.mean()

0.39926557981783978

Créez un array bi-dimensionnel avec des données aléatoires
Calculez la moyenne par colonne

In [17]:
arr9=np.random.randn(10000000).reshape(100000,100)

In [18]:
#axis=0 en colonnes
#axis=1 en lignes
%time arr_moyennes=arr9.mean(axis=0)
%time arr_moyennes=np.mean(arr9,axis=0)

Wall time: 13.5 ms
Wall time: 9.01 ms


In [19]:
arr_moyennes.shape

(100,)

Générer une matrice simple et sauvegarder cette matrice dans array.npy puis dans array.txt


In [20]:
#mon répertoire de travail
%pwd

'C:\\Users\\Emmanuel\\Desktop\\formation python'

In [21]:
%time np.save("mon_array",arr9)

Wall time: 306 ms


In [22]:
%time np.savetxt("mon_array.txt",arr9)

Wall time: 11 s


In [23]:
del arr9

In [24]:
%time arr9=np.load("mon_array.npy")

Wall time: 82 ms


In [25]:
arr9.shape

(100000, 100)